version: 2.0
jobs:
  build:
    docker:
      - image: docker:latest

    working-directory: ~/repo
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -f ./dev/Dockerfile -t jshm101/jr-site-reverse-proxy:dev .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jshm101/jr-site-reverse-proxy:dev
  deploy:
    docker:
      - image: alpine:latest
    working_directory: ~/
    steps:
      - run:
          name: Add SSH client
          command: |
            apk add openssh
      - run:
          name: SSH & run deploy script
          command: |
            ssh -o StrictHostKeyChecking=no root@174.138.117.81 "./deploy-app.sh"
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
